services:
  - type: web
    name: rune-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    branch: main
    repo: https://github.com/TysonTheNugget/runebuy
